# Generated by Django 4.2.17 on 2025-01-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JwtKeyPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private_key", models.TextField()),
                ("public_key", models.TextField()),
                ("algorithm", models.CharField(max_length=32)),
            ],
        ),
    ]
