# Generated by Django 4.2.17 on 2024-12-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relyingparty",
            name="client_secret",
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
